### PR TITLE
Add support for OCaml 5.3

### PR DESCRIPTION
**Pull request by kit-ty-kate**
effect is now a keyword

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
cc @gerdstolpmann

**Comment by kit-ty-kate** [comment]
ping @gerdstolpmann if you have some time. If not is there anyone else able to do a release?

**Comment by cspiel** [comment]
@kit-ty-kate: Sorry, but I totally forgot that I have merge rights.
THX for your patch.

**Comment by kit-ty-kate** [comment]
no worries! If you'd be able to push a release commit similar to https://github.com/ocaml-omake/omake/pull/156 and push a tag, i'm happy doing the publishing part of the release (submit to opam-repository) if that helps

**Comment by cspiel** [comment]
AFAICT it looks good.
If something is odd gimme a buzz.
And don't tell me I'm terrific.

**Comment by kit-ty-kate** [comment]
Apart from a bit of parsing issues (fixed by https://github.com/ocaml-omake/omake/pull/161) i had no problem so far. I've opened the PR in: https://github.com/ocaml/opam-repository/pull/27043

**Pull request merged**
