### PR TITLE
Install: do not interpret the environment variables PREFIX, BINDIR, LIBDIR.

### PR DESCRIPTION
**Pull request by gerdstolpmann**
There is still INSTALL_ROOT (as documented).

### CODE REVIEW

**Comment by rgrinberg** [comment]
For opam, we'd ideally generate an .install file detailing the exact artifacts we'd like to install. But this is good  for non opam people too.

**Comment by rgrinberg** [comment]
What about this usage of PREFIX:

https://github.com/rgrinberg/omake/blob/master/mk/defaults#L14-L15

Is it just an artifact?

**Comment by gerdstolpmann** [comment]
This PREFIX only sets the default. It is normally overridden in $(CONFIG_FILE) and set to the configured prefix. The whole point is that we do not `$(getenv PREFIX)` after including the config file.

Btw, apparently you did not sync your repository.

**Comment by rgrinberg** [comment]
OK, thanks. I did sync my repository now. Although that shouldn't matter for submitting an opam package (I pointed it at this official repository anyway)

**Pull request merged**
