### PR TITLE
Add a Travis CI setting

### PR DESCRIPTION
**Pull request by y-yu**
Hello.

I think OMake needs CI(Continuous Integration). So I wrote a setting file for [Travis CI](https://travis-ci.org/)
## What is Travis CI?

Wikipedia says

> Travis CI is a hosted, distributed continuous integration service used to build and test software projects hosted at GitHub.

See also https://travis-ci.org/

This `.travis.yml` will do the following: 
1. install OCaml
2. `./configure`
3. `make`
4. `make install`
5. change the `test` directory
6. `omake`

See also [.travis.yml](https://github.com/y-yu/omake/blob/master/.travis.yml)
## Example Result

https://travis-ci.org/y-yu/omake/builds/165228847

Thanks.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good, but why didn't you use the opam based skeleton? I know omake doesn't require opam, but it would be nice to make sure our opam scripts are working as well. They will also install the necessary dependencies for us on Windows for example.

Also, which versions of OCaml this travis script is testing against? We should support older OCaml's. I'm not sure how old we want to go. Gerd might be able to answer that.

**Comment by gerdstolpmann** [comment]
I think we should add 4.04.0 which just came out.

y-yo: what do I need to do to enable travis once I merged this?

**Comment by y-yu** [comment]
Sorry for very late my reply.

>  what do I need to do to enable travis once I merged this?

1. You(this repository's owner) access [Travis CI website](https://travis-ci.org/) and sign in by GitHub account
2. You click **ocaml-omake** organization from [your profile page on Travis CI](https://travis-ci.org/profile/)
3. You click the button (like a below image) of **omake** repository from [the organization page on Travis CI](https://travis-ci.org/profile/ocaml-omake)
image

**Comment by gerdstolpmann** [comment]
fyi, I activated travis

**Pull request merged**
